### ISSUE TITLE
Wrong content-type on webhook 

### ISSUE THREAD

**Issue by MaximeBr** [Combodo/combodo-webhook-integration#1]
Hello, so I've found this issue while trying to do a POST Webhook.

# Issue 

When trying to set a POST Webhook with `Content-type: application/json`, the webhook seems to trigger with an `application/x-www-form-urlencoded`.

While observing the packet with wireshark, `Content-length` is also 0 while there is a payload (json).

## Configuration 
![param webhook itop](https://user-images.githubusercontent.com/29253467/157292920-9ff57927-ba9f-49e0-a168-bea1d789d1db.PNG)

## Notification history of webhook
![notification itop](https://user-images.githubusercontent.com/29253467/157294364-91ca56aa-2683-4436-9923-689c5dfb94b3.PNG)

## Wireshark screenshot 

![Capture wireshark](https://user-images.githubusercontent.com/29253467/157294382-caeb8e4b-2693-4218-986b-6ff01b741086.PNG)

Did I do something wrong while setting up the webhook ?

Kind regards,

Maxime

**Comment by Molkobain** [comment]
Hello Maxime,

This seems odd indeed. Can you tell the exact iTop version and webhook extension version you are using?

Thanks,
Guillaume

**Comment by MaximeBr** [comment]
I'm using :
- Itop 2.7.4
- php 7.2.24

I tried with webhook 1.0.0 from Itop Hub and 1.1.0 directly from github.

**Comment by MaximeBr** [comment]
I found the solution !
I finally tried to update my php version to 7.4 and it works.

Thanks for checking.

Maxime

**Comment by Molkobain** [comment]
Sorry I didn't had time to check the past few days. But glad to see you found a solution!

Cheers,
Guillaume
